# frozen_string_literal: true

require "test_helper"

# Report-only, corpus-wide. What is pinned: generated-without-verified is
# listed wherever it lives, attested and hand-written concepts are not, and
# nothing here ever refuses — unverified is the truth, not a defect.
class AttestationTest < OKF::Pro::TestCase
  def test_lists_generated_concepts_awaiting_a_read
    with_bundle do |b|
      b.concept("reference/pricing.md", type: "Briefing",
        generated: { by: "claude", at: "2026-08-10" })

      rows = OKF::Pro::Attestation.report(b.bundle_path)

      assert_equal 1, rows.size
      assert_match(%r{reference/pricing: generated by claude on 2026-08-10 \[unverified\] — awaiting}, rows.first)
    end
  end

  # Broader than the pairing check on purpose: only briefings owe the board a
  # To-read line, but any generated concept awaits its read.
  def test_reaches_beyond_reference
    with_bundle do |b|
      b.concept("learnings/a-rule.md", type: "Learning",
        generated: { by: "claude", at: "2026-08-10" })

      assert_equal 1, OKF::Pro::Attestation.report(b.bundle_path).size
    end
  end

  def test_an_attested_concept_is_not_listed
    with_bundle do |b|
      b.concept("reference/pricing.md", type: "Briefing",
        generated: { by: "claude/opus-5", at: "2026-08-10" },
        verified: { by: "human:owner", at: "2026-08-11" })

      assert_empty OKF::Pro::Attestation.report(b.bundle_path)
    end
  end

  # §5.3 again, and this list is where it is most visible: an owner reads this
  # to decide what to look at next, and "a machine rechecked it" is exactly the
  # distinction they need. Testing `verified` for truthiness dropped the row
  # entirely, which told them there was nothing left to read.
  def test_a_machine_confirmed_concept_is_still_listed_and_says_which_tier
    with_bundle do |b|
      b.concept("reference/pricing.md", type: "Briefing",
        generated: { by: "claude/opus-5", at: "2026-08-10" },
        verified: { by: "process:nightly-recheck", at: "2026-08-11" })

      rows = OKF::Pro::Attestation.report(b.bundle_path)

      assert_equal 1, rows.size
      assert_match(/\[machine-confirmed\]/, rows.first)
    end
  end

  def test_a_hand_written_concept_owes_nothing
    with_bundle do |b|
      b.concept("glossary/term.md", type: "Term")

      assert_empty OKF::Pro::Attestation.report(b.bundle_path)
    end
  end
end
