# frozen_string_literal: true

require "test_helper"

# `okf pro state` — the verb the measurement asked for.
#
# A real session adding one task to a seeded bundle spent 40.9% of its tool
# output rediscovering state that the gates already compute, and called no
# `okf pro` verb at all. This is that state, in one call, and its contract is
# cheap-by-default: the payload below reads `board.md`, `log.md` and two
# directory globs, and parses no concept. `--full` is where the corpus is.
class CLIStateTest < OKF::Pro::TestCase
  TODAY = Date.today

  def populated(b)
    b.concept("reference/movers-quote.md", type: "Briefing",
      body: "# Summary\n\nAn agent read the source so nobody else had to. Yet.\n",
      generated: { by: "claude", at: "2026-08-01" })
    b.write("projects/home-move/index.md", "# Home move\n\nOngoing.\n")
    b.in_flight("[/projects/home-move/](/projects/home-move/index.md) — call the movers")
    b.inbox("#{TODAY - 4} — the invoice from acme",
      "#{TODAY - 1} — Resolve: [/reference/movers-quote.md] says X, the term says Y")
    b.board_lines("Backlog", "sort out the storage unit")
    b.board_lines("Waiting", "Landlord: inspection — chase #{TODAY - 3}")
    b.board_lines("To read", "[/reference/movers-quote.md] — agent-summarised, unread")
    b.board_lines("Deadlines", "#{TODAY + 2} — insurance renewal lapses")
  end

  # ── human output, which is the default ──────────────────────────────────

  test "the human payload carries every board counter in one line" do
    with_bundle do |b|
      populated(b)
      run = run_cli([ "state", b.path ])

      assert_equal OKF::Pro::PASS, run.status
      assert_empty run.err
      assert_match(/in flight 1\/5/, run.out)
      assert_match(/backlog 1/, run.out)
      assert_match(/waiting 1 \(1 past chase\)/, run.out)
      assert_match(/inbox 2 \(oldest 4d\)/, run.out)
      assert_match(/to read 1/, run.out)
      assert_match(/deadlines 1/, run.out)
      assert_match(/conflicts open 1/, run.out)
    end
  end

  test "a deadline nothing is in flight against is named, not merely counted" do
    with_bundle do |b|
      populated(b)
      out = run_cli([ "state", b.path ]).out

      assert_match(/Deadlines within 7d with nothing in flight against them:/, out)
      assert_match(/insurance renewal lapses/, out)
    end
  end

  test "the log line says which day is newest and whether today is open" do
    with_bundle do |b|
      populated(b)
      b.log_day("2026-08-10", "* A thing.")
      out = run_cli([ "state", b.path ]).out

      assert_match(/newest day 2026-08-10/, out)
      assert_match(/journal for #{TODAY} not opened/, out)
    end
  end

  test "open projects are listed, because a name is what the next verb takes" do
    with_bundle do |b|
      populated(b)

      assert_match(/Open projects \(1\): home-move/, run_cli([ "state", b.path ]).out)
    end
  end

  # A header that disagrees with the section under it is Rule 3's refusal, and
  # a reader who is shown the count without the disagreement is being shown a
  # number the cap check is about to reject.
  test "a header that lies about its own section is called out" do
    with_bundle do |b|
      b.in_flight("a thing", "another thing").budget(declared: 5, cap: 5)

      assert_match(/header declares 5 in flight and the section holds 2/, run_cli([ "state", b.path ]).out)
    end
  end

  # ── the snapshot's free counters ────────────────────────────────────────
  #
  # Two of the twelve can only be recomputed by parsing the bundle. They are
  # printed from the last logged line and LABELLED as of that day — a stale
  # number read as current is worse than no number.

  test "the two corpus counters are labelled by the day they were logged" do
    with_bundle do |b|
      populated(b)
      b.snapshot_on("2026-08-10")
      out = run_cli([ "state", b.path ]).out

      assert_match(/As of 2026-08-10, the last logged snapshot — unverified briefings 1/, out)
      assert_match(/`--full` recomputes these live/, out)
    end
  end

  test "a bundle with no snapshot yet says so rather than printing zeroes" do
    with_bundle do |b|
      populated(b)

      assert_match(/^Last snapshot: none yet$/, run_cli([ "state", b.path ]).out)
    end
  end

  # ── --full ──────────────────────────────────────────────────────────────

  test "--full recomputes the corpus counters and reports the pairing invariants" do
    with_bundle do |b|
      populated(b)
      out = run_cli([ "state", b.path, "--full" ]).out

      assert_match(/Live from the corpus — unverified briefings 1/, out)
      assert_match(/Pairing — the board and the work are in step\./, out)
      assert_match(/Awaiting the owner's read \(1\):/, out)
      assert_match(%r{reference/movers-quote: generated by claude}, out)
    end
  end

  test "--full names a pairing failure the default payload cannot see" do
    with_bundle do |b|
      b.write("projects/orphan/index.md", "# Orphan\n\nOpen and unlinked.\n")
      out = run_cli([ "state", b.path, "--full" ]).out

      assert_match(%r{Pairing — 1 finding\(s\):}, out)
      assert_match(%r{projects/orphan has no board line}, out)
    end
  end

  test "the default payload does not carry the corpus block at all" do
    with_bundle do |b|
      populated(b)

      refute_match(/Live from the corpus/, run_cli([ "state", b.path ]).out)
    end
  end

  # ── --json / --pretty ───────────────────────────────────────────────────

  test "--json emits one object with the board, the log and the projects" do
    with_bundle do |b|
      populated(b)
      run = run_cli([ "state", b.path, "--json" ])

      assert_equal OKF::Pro::PASS, run.status
      payload = JSON.parse(run.out)

      assert_equal 1, payload["board"]["in flight"]
      assert_equal 5, payload["board"]["cap"]
      assert_equal 2, payload["board"]["inbox"]
      assert_equal [ "home-move" ], payload["projects"]["open"]
      assert_nil payload["last snapshot"]
      refute payload.key?("full"), "the cheap payload must not carry the corpus block"
    end
  end

  test "--json --full adds the corpus block behind one parse" do
    with_bundle do |b|
      populated(b)
      payload = JSON.parse(run_cli([ "state", b.path, "--json", "--full" ]).out)

      assert_equal 1, payload["full"]["unverified briefings"]
      assert_equal [ "reference/movers-quote" ], payload["full"]["unverified"].map { |row| row[/\A\s*(\S+):/, 1] }
    end
  end

  test "--pretty is --json, indented" do
    with_bundle do |b|
      populated(b)
      run = run_cli([ "state", b.path, "--pretty" ])

      assert_equal OKF::Pro::PASS, run.status
      assert_match(/\A\{\n  "root"/, run.out)
      assert_kind_of Hash, JSON.parse(run.out)
    end
  end

  # ── what this verb is not ───────────────────────────────────────────────

  # Friction is telemetry about the tooling, not state of the bundle, and this
  # verb's contract is that its default payload reads `board.md`, `log.md` and
  # two globs. The friction log was a fourth source — append-only, nothing
  # prunes it — read on every call and never rendered for a human at all.
  test "the friction log is not one of this verb's sources" do
    with_bundle do |b|
      OKF::Pro::Friction.record(b.bundle_path, "edit", "board.md")
      path = b.path

      refute_includes JSON.parse(run_cli([ "state", "--json", path ]).out).keys, "friction"
      assert_equal 1, JSON.parse(run_cli([ "friction", "--json", path ]).out)["recorded"]
    end
  end

  # ── the exits ───────────────────────────────────────────────────────────

  test "a directory holding no bundle is exit 2, not an empty report" do
    Dir.mktmpdir do |dir|
      run = run_cli([ "state", dir ])

      assert_equal OKF::Pro::BLOCK, run.status
      assert_match(/holds no OKF bundle/, run.err)
    end
  end

  test "a bundle with no board is exit 2, because there is nothing to answer with" do
    with_bundle do |b|
      path = b.path
      File.delete(File.join(b.bundle_path, "board.md"))
      run = run_cli([ "state", path ])

      assert_equal OKF::Pro::BLOCK, run.status
      assert_match(/has no board\.md to read/, run.err)
    end
  end

  # The one branch that only shows up on a day somebody worked.
  test "the log line says the journal is open once today's day exists" do
    with_bundle do |b|
      populated(b)
      path = b.path
      run_cli([ "journal", "open", path ])

      assert_match(/journal for #{TODAY} open$/, run_cli([ "state", path ]).out)
    end
  end

  # A verb that cannot run exits 2, never 1: 1 means findings, and a pipeline
  # that cannot tell a broken bundle from a broken checker learns to ignore
  # both. The trigger is real — board.md replaced by a directory makes the read
  # raise EISDIR.
  test "a crash while reading exits 2 and names the cause" do
    with_bundle do |b|
      path = b.path
      board = File.join(b.bundle_path, "board.md")
      File.delete(board)
      Dir.mkdir(board)
      run = run_cli([ "state", path ])

      assert_equal OKF::Pro::BLOCK, run.status
      assert_match(/could not run \(Errno::EISDIR/, run.err)
      assert_match(/Exit 2, for the reason `audit` gives/, run.err)
    end
  end

  test "an unknown flag is a usage error rather than a second directory" do
    with_bundle do |b|
      run = run_cli([ "state", b.path, "--nope" ])

      assert_equal OKF::Pro::BLOCK, run.status
      assert_match(/invalid option: --nope/, run.err)
      assert_empty run.out
    end
  end

  # The flags are parsed BEFORE the positional check, which refuses any second
  # argument — without that ordering this is two directories and an exit 2.
  test "a flag after the directory is a flag, not a second directory" do
    with_bundle do |b|
      run = run_cli([ "state", b.path, "--json" ])

      assert_equal OKF::Pro::PASS, run.status
      assert_kind_of Hash, JSON.parse(run.out)
    end
  end

  # OptionParser's "officious" --help calls `exit` from inside the parse. In a
  # gem whose whole subject is which exit code a gate returns, a library call
  # that exits the process is not acceptable, so both are declared.
  test "--help prints the usage and exits 0 without exiting the process" do
    run = run_cli([ "state", "--help" ])

    assert_equal OKF::Pro::PASS, run.status
    assert_match(/\AUsage: okf pro <command>/, run.out)
  end

  test "--version prints the version rather than parsing a bundle" do
    run = run_cli([ "state", "--version" ])

    assert_equal OKF::Pro::PASS, run.status
    assert_equal "#{OKF::Pro::VERSION}\n", run.out
  end

  # The CI verbs emit no MARKER: they are read by a person and a pipeline, not
  # by the wrapper that authenticates a gate.
  test "state emits no enforcer marker" do
    with_bundle do |b|
      refute run_cli([ "state", b.path ]).identified?
    end
  end
end
